# Generated by Django 2.2.6 on 2019-10-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.IntegerField(default=1),
        ),
    ]
