# Generated by Django 2.2.6 on 2019-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_room_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='flag',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=220),
        ),
    ]
