# Generated by Django 2.2.6 on 2019-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20191124_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='flag2',
            field=models.BooleanField(default=False),
        ),
    ]
