# Generated by Django 2.2.6 on 2019-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20191124_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='flag2',
        ),
        migrations.AddField(
            model_name='room',
            name='booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
